include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Style
    prefer_single_quotes: true
    always_use_package_imports: true
    directives_ordering: true
    sort_constructors_first: true

    # Code quality
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true
    unnecessary_this: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true

    # Safety
    cancel_subscriptions: true
    close_sinks: true
    use_build_context_synchronously: true

    # Performance
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    # Architecture discipline
    depend_on_referenced_packages: true
    implementation_imports: true
    avoid_relative_lib_imports: true
