name: my_store
description: "My Store"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Utilities
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets
  # assets:
  #   - assets/images/
