name: my_store
description: "My Store"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # UI
  cupertino_icons: ^1.0.8

  # Utilities
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.3

  # Lints
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets
  # assets:
  #   - assets/images/
